### ISSUE TITLE
Admin Pannel not properly work in mobile view

### ISSUE THREAD

**Issue by ceo-pingu** [siddhesh321995/delta-techno-tide#13]
Admin Pannel not properly work in mobile view

**Comment by siddhesh321995** [comment]
Duplicate bug closing the other bug posted #16 : 1. Remove tables from all view pages

**Comment by siddhesh321995** [comment]
@ceo-pingu  @aniket1712 please do suggest some views for presenting table data to admin
In table like struct but not table tag (Currently we are using table tag itself)

**Comment by ceo-pingu** [comment]
http://bootsnipp.com/snippets/featured/no-more-tables-respsonsive-table
@siddhesh321995 @aniket1712 
See this link....

**Comment by siddhesh321995** [comment]
@ceo-pingu Nice suggestion.
I think we should be using this

**Comment by siddhesh321995** [comment]
Resolved and Tested locally
Will be updated in next build
