### ISSUE TITLE
Dashboard Changes After regression testing

### ISSUE THREAD

**Issue by ceo-pingu** [siddhesh321995/delta-techno-tide#16]
1. <strike>Remove tables from all view pages</strike>

2. index what not changing

3. Serial Number wrong order in view contact

4. Single para settings not working

**Comment by siddhesh321995** [comment]
Issue fixed :
**4. Single para settings not working**

**Comment by siddhesh321995** [comment]
Issue fixed :
2. index what not changing

**Comment by siddhesh321995** [comment]
Issue fixed :
3. Serial Number wrong order in view contact

**Comment by siddhesh321995** [comment]
Resolved and tested locally
Will upload in today's next build
