### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by siddhesh321995** [siddhesh321995/delta-techno-tide#20]
Suggest some design or create a static about us page
Regarding 2 owners of the company

**Comment by ceo-pingu** [comment]
**http://webdeveloperbareilly.in/blog/demo/Bootstrap-About-Us-Page-Design.html**

**Comment by siddhesh321995** [comment]
Nice design
I would rather suggest to take 1 row per member entry in that container rather than showing 2 members in 1 row

**Comment by siddhesh321995** [comment]
Static about us page is created
Make it dynamic, create a table in DB and retrieve data from it

**Comment by ceo-pingu** [comment]
Ohk...Boss

**Comment by siddhesh321995** [comment]
About us page made dynamic tested online
