### ISSUE TITLE
Main header font-color change

### ISSUE THREAD

**Issue by siddhesh321995** [siddhesh321995/delta-techno-tide#3]
Ha color kon baap change karnar??
No black color will be there for font
Check this :
![untitled](https://cloud.githubusercontent.com/assets/20275358/19014604/fe82384a-880e-11e6-8ead-a6608802cd75.png)

**Comment by siddhesh321995** [comment]
Same one on history page !

**Comment by ceo-pingu** [comment]
Fix issue of font color
